name: Create & Push Logstash docker image with postgres and aws-elastic output plugin

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch:
  push:
    branches: [ 7.14-aws ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set branch name to a variable
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.5.1
      - name: Login to DockerHub
        uses: docker/login-action@v1.10.0 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.6.1
        with:
          push: true
          tags: cytechmobile/logstash-postgres:${{ steps.vars.outputs.short_ref }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
