name: Create & Push Logstash docker image with postgres and aws-elastic output plugin

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set branch name to a variable
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: cytechmobile/logstash-postgres:${{ steps.vars.outputs.short_ref }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
